### ISSUE TITLE
Test Installing ACUNAO on a PC

### ISSUE THREAD

**Issue by code-Adrastos** [luquelab/ACUNAO-AI#25]
Installing ACUNAO on a PC to ensure it works on both Mac and PC, document the differences.

**Comment by code-Adrastos** [comment]
Open powershell as administrator and run >> "Get-ExecutionPolicy" to see current policy.
Run >> "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser" and change the execution policy as needed.
You can switch the execution policy back to Restricted using >> "Set-ExecutionPolicy Restricted -Scope CurrentUser"

Creating a virtual environment in the ACUNAO folder >> "python -m venv venv"

If running in a terminal use >> "venv\Scripts\activate"  to activate the virtual environment you have created.
If running in the command line use >> "\venv\Scripts\Activate.ps1" to activate the virtual environment you have created.

Lastly, within the virtual environment, run the streamlit application using >> "streamlit run src/app.py"

When done, deactivate the virtual environment in either command line or terminal entering >> "deactivate"

**Comment by TjanMichela** [comment]
Since the installation works on Windows (Latim's laptop), the issue is resolved.
